#!/bin/bash

# Create secure_vault directory in the user's home
# -p option creates the direcory if it does not exist, skips if it exists
mkdir -p ~/secure_vault

# Create files and add welcome messages using I/O redirection
# > here > is used to create the file and write to it using I/O redirection
# ~ denotes the home directory of the user
echo "Welcome to the Keys Vault" > ~/secure_vault/keys.txt 
echo "Welcome to the Secrets Vault" > ~/secure_vault/secrets.txt
echo "Welcome to the Logs Vault" > ~/secure_vault/logs.txt

# Print success message
echo "Secure vault setup completed successfully."

# List all files in long format
# -l option  is used to display long format listing of the specified directory
ls -l ~/secure_vault


## to run this file assignt it execution permision using "chmod +x vault_setup.sh" or using bash command followed by the script name
## for more info. review the README.md file in the root of the repository 
